config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update]do
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
      get :daily_posts
    end
  end

  resources :notifications, only: [:update]
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]
    @how = params[:how]

    if @range == "User"
      @users = User.search_for(@word, @how)
    else
      @books = Book.search_for(@word, @how)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
    <%= form_with url: search_path, method: :get, local: true do %>
        <%= text_field_tag :word, params[:word] %>
        <%= select_tag :range, options_for_select(["User", "Book"])%>
        <%= select_tag :how, options_for_select([["完全一致", "perfect"], ["前方一致", "forward"], ["後方一致", "backward"], ["部分一致", "partial"]]) %>
        <%= submit_tag "検索" %>
    <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @range == 'User' %>
  <h3>Users search for "<%= @word %>"</h3>
  <%= render 'users/index', users: @users%>
<% elsif @range == 'Book' %>
  <h3>Books search for "<%= @word %>"</h3>
  <%= render 'books/index', books: @books %>
<% end %>